version: "3.0"
services:
  firebase:
    build: .
    image: firebase-emulator:firebase-emulator
    environment:
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
    volumes:
      - .:/src
    ports:
      - 4400:4400
      - 4500:4500
      - 5000:5000
      - 5001:5001
      - 8001:8001
      - 8080:8080
      - 9000:9000
    command: sh