label: Relay

# Admin
admin: [0.0.0.0, 3001]
admin-insecure-mode: true

# Load toolbox plugin
plugin:
  - firebase_push_notification
  - acapy-plugin-pickup

plugin-config-value:
  - firebase.server_token=${FIREBASE_SERVER_TOKEN}

# Transport
inbound-transport:
  - [http, 0.0.0.0, 3000]
  - [ws, 0.0.0.0, 3003]
outbound-transport: http
endpoint:
  - http://relay:3000
  - ws://relay:3003

# Ledger
no-ledger: true

# Connections
debug-connections: true
debug-credentials: true
debug-presentations: true
auto-accept-invites: true
auto-accept-requests: true
connections-invite: true
log-level: debug

# Mediation
open-mediation: true

# Queue
enable-undelivered-queue: true
