version: "3"

services:

  relay:
    build:
      context: ../
      dockerfile: ./int/Dockerfile
    environment:
      ACAPY_TOOLBOX_LOG_LEVEL: DEBUG
    ports:
      - "3001:3001"
    command: >
      start --arg-file int-testing-default.yml

  agent-bob:
    image: acapy-toolbox
    build:
      context: ../
      dockerfile: ./demo/Dockerfile
    volumes:
      - ./configs:/home/indy/configs:ro,z
    environment:
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3006:3006"
      - "3002:3002"
    command: start --arg-file ./configs/bob.yml