version: "3"

services:

  tunnel-mediator:
    image: dbluhm/agent-tunnel
    command: -s reverse-proxy:80 -p 4040 -h ${AGENT_TUNNEL_HOST}
    ports:
      - 4040:4040
    depends_on:
      - reverse-proxy
  reverse-proxy:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      AGENT_HTTP: "http://mediator:3000"
      AGENT_WS: "http://mediator:3003"
    ports:
      - 80:80
    volumes:
      - ./mediator.conf.template:/etc/nginx/templates/default.conf.template:z
    depends_on:
      - mediator
  mediator:
    build:
      context: ../
      dockerfile: ./int/Dockerfile.int.yml
    volumes:
      - ./acapy-endpoint.sh:/acapy-endpoint.sh:ro,z
    environment:
      - ACAPY_TOOLBOX_LOG_LEVEL=DEBUG
      - DEVICE_TOKEN=${DEVICE_TOKEN}
      - TUNNEL_ENDPOINT=http://tunnel-mediator:4040
    ports:
      - "3001:3001"
    entrypoint: >
      /bin/sh -c '/acapy-endpoint.sh aca-py "$$@"' --
    command: >
      start --arg-file int-testing-default.yml
        --plugin-config-value firebase.server_token=${FIREBASE_SERVER_TOKEN}
        --plugin-config-value pickup.persistence=redis
        --plugin-config-value pickup.redis.ttl_hours=168
        --plugin-config-value pickup.redis.server=redis://redis:6379/0
        --webhook-url http://webhook-listener:8080
    depends_on:
      redis:
        condition: service_healthy

  tunnel-alice:
    image: dbluhm/agent-tunnel
    command: -s agent-alice:4002 -p 4042 -h ${AGENT_TUNNEL_HOST}
  agent-alice:
    image: acapy-toolbox
    build:
      context: ../
      dockerfile: ./demo/Dockerfile.demo.yml
    volumes:
      - ./acapy-endpoint.sh:/acapy-endpoint.sh:ro,z
      - ./configs:/home/indy/configs:ro,z
    environment:
      TUNNEL_ENDPOINT: http://tunnel-alice:4042
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3007:3007"
      - "4002:4002"
    entrypoint: >
      /bin/sh -c '/acapy-endpoint.sh aca-py "$$@"' --
    command: start --arg-file ./configs/alice.yml --webhook-url http://webhook-listener:8080

  redis:
      image: "redis:alpine"
      ports:
      - "6379:6379"
      volumes:
        - ./redis-data:/var/lib/redis
        - ./redis.conf:/etc/redis/redis.conf
      environment:
      - REDIS_REPLICATION_MODE=master
      healthcheck:
        test: nc -z localhost 6379 || exit -1
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
  webhook-listener:
    image: mendhak/http-https-echo:18
    environment:
      - HTTP_PORT=8080
